### ISSUE TITLE
torch_scatter库的paddle转换

### ISSUE THREAD

**Issue by kongdebug** [PaddlePaddle/PaConvert#255]
[torch_scatter](https://github.com/rusty1s/pytorch_scatter) 是一个torch的扩增库，目前在科学计算、神经辐射场等领域均有用到，例如第四期黑客松的赛题[No.173 Point-NeRF](https://github.com/PaddlePaddle/community/blob/master/hackthon_4th/%E3%80%90PaddlePaddle%20Hackathon%204%E3%80%91%20%E6%A8%A1%E5%9E%8B%E5%A5%97%E4%BB%B6%E5%BC%80%E6%BA%90%E8%B4%A1%E7%8C%AE%E4%BB%BB%E5%8A%A1%E5%90%88%E9%9B%86.md#task173)就涉及torch_scatter中的scatter_min算子，无法通过paddle复现，像简单的scatter_add倒是可以组合复现，但是也很大的增加了复现的成本。请问您这边有计划推出torch_scatter的paddle转换吗

**Comment by GreatV** [comment]
这个库都是自定义算子，目前应该还不能通过pacovert的转换，感觉还是得靠手写自定义算子来实现。

**Comment by kongdebug** [comment]
> 这个库都是自定义算子，目前应该还不能通过pacovert的转换，感觉还是得靠手写自定义算子来实现。

OK 我close了
