### ISSUE TITLE
【社区治理】co63oc 发起 Committer 身份申请

### ISSUE THREAD

**Issue by co63oc** [PaddlePaddle/PaConvert#262]
##### 基本信息
| 申请人 GitHub ID | PaConvert Repo 整体 merge PR 数 | PaConvert Repo 整体 review PR 数 | PaConvert Repo 整体报告 Issue 数 |
| - | - | - | - |
| @co63oc | [50](https://github.com/PaddlePaddle/PaConvert/pulls?q=is%3Apr+author%3Aco63oc+is%3Aclosed) | 0 | 0 |

##### 社区贡献概况
以下是此前在本 repo 里做过的贡献：
实现若干算子转换规则

##### 高质量 merge PR 展示
| PR 号 | PR 标题 | PR 简介 | Reviewer |
| - | - | - | - |
| #197 | 转换规则 No. 196/197/232/233/319 | - | zhwesky2010 |
| #198 | 转换规则 No. 323/333 | - | zhwesky2010 |
| #199 | 转换规则 No. 349/350 | - | zhwesky2010 |

##### 担保人意见
@Ligoml @luotao1

**Comment by luotao1** [comment]
+1 同意， @co63oc 在以下任务中已经完成了200多个API的转换工作：
- https://github.com/PaddlePaddle/PaConvert/issues/112

**Comment by zhwesky2010** [comment]
+1 同意

@co63oc 在 PaConvert Repo中贡献了很多高质量PR和代码，对自己负责的API有仔细分析，同时不局限于该API，能主动修复既往API映射文档或转写规则Bug，体现了精雕细磨的精神。相信以后也会继续为 PaConvert 做出更多有价值的贡献。

**Comment by zhwesky2010** [comment]
欢迎成为 committer，已添加对应权限，请注意查收:-)祝贺！

**Comment by Ligoml** [comment]
恭喜恭喜~
